package pr.markodojkic.prodavnicaoieadmin.order.entity;

import javax.persistence.*;

@Entity
@Table(name = "orders") //Because 'order' is reserved word in sql
public class Order {
    public enum ShippingMethods {
        PERSONAL("Лично преузимање"),
        COURIER("Курирска служба"),
        POST("Пошта");

        private String databaseName;

        ShippingMethods(String dN) {
            this.databaseName = dN;
        }

        public String getDatabaseName(){
            return databaseName;
        }
    }

    public enum Status {
        PENDING("Текућа"),
        CANCELED("Отказана"),
        COMPLETED("Завршена");

        private String databaseName;

        Status(String sN){
            this.databaseName = sN;
        }

        public String getDatabaseName(){
            return databaseName;
        }
    }

    @Id
    @Column(name = "order_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Generated by sql database AUTO_INCREMENT
    private int id;
    @Column(name = "account_id")
    private int account_id;
    @Column(name = "shipping_method")
    private ShippingMethods shippingMethod;
    @Column(name = "status")
    private Status status;

    public Order() { }

    public Order(int id, int account_id, ShippingMethods shippingMethod, Status status) {
        this.id = id;
        this.account_id = account_id;
        this.shippingMethod = shippingMethod;
        this.status = status;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getAccount_id() {
        return account_id;
    }

    public void setAccount_id(int account_id) {
        this.account_id = account_id;
    }

    public ShippingMethods getShippingMethod() {
        return shippingMethod;
    }

    public void setShippingMethod(ShippingMethods shippingMethod) {
        this.shippingMethod = shippingMethod;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }
}
