package pr.markodojkic.prodavnicaoieadmin.account.entity;

import javax.persistence.*;

@Entity
@Table(name = "account")
public class Account {
    @Id
    @Column(name = "account_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Generated by sql database AUTO_INCREMENT
    private int id;
    @Column(name = "name")
    private String name;
    @Column(name = "surname")
    private String surname;
    @Column(name = "password_hash")
    private String password_hash;
    @Column(name = "email_address")
    private String email;
    @Column(name = "phone_number")
    private String phoneNumber;
    @Column(name = "mobile_phone_number")
    private String mobilePhoneNumber;
    @Column(name = "delivery_address")
    private String deliveryAddress;
    @Column(name = "delivery_address_pak")
    private String deliveryAddressPAK;

    public Account(){}

    public Account(int id, String name, String surname, String password_hash, String email, String phoneNumber, String mobilePhoneNumber, String deliveryAddress, String deliveryAddressPAK) {
        this.id = id;
        this.name = name;
        this.surname = surname;
        this.password_hash = password_hash;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.mobilePhoneNumber = mobilePhoneNumber;
        this.deliveryAddress = deliveryAddress;
        this.deliveryAddressPAK = deliveryAddressPAK;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getPassword_hash() {
        return password_hash;
    }

    public void setPassword_hash(String password_hash) {
        this.password_hash = password_hash;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getMobilePhoneNumber() {
        return mobilePhoneNumber;
    }

    public void setMobilePhoneNumber(String mobilePhoneNumber) {
        this.mobilePhoneNumber = mobilePhoneNumber;
    }

    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    public String getDeliveryAddressPAK() {
        return deliveryAddressPAK;
    }

    public void setDeliveryAddressPAK(String deliveryAddressPAK) {
        this.deliveryAddressPAK = deliveryAddressPAK;
    }

    @Override
    public String toString() {
        return "{" +
                "id:" + id +
                ",name:'" + name + '\'' +
                ",surname:'" + surname + '\'' +
                ",password_hash:'" + password_hash + '\'' +
                ",email:'" + email + '\'' +
                ",phoneNumber:'" + phoneNumber + '\'' +
                ",mobilePhoneNumber:'" + mobilePhoneNumber + '\'' +
                ",deliveryAddress:'" + deliveryAddress + '\'' +
                ",deliveryAddressPAK:'" + deliveryAddressPAK + '\'' +
                '}';
    }
}
